name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-09"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNzEyZTI1MjUtNWVhYS00MTYyLWI0MDMtYTRlNWUyMTMxYjBiIiwidGVuYW50X2lkIjoiNDBkZTI5MTMxYmM2NjAwOGEyYjE1YTJkNjBkMDAxZTQyYmI1Nzk5MDhhMGM5ZTZiY2M3ZjRkODZkNmRiYjdhNyIsImludGVybmFsX3NlY3JldCI6ImNiYjRlNzhlLWFkNDMtNGVjZC04M2IzLTIzOGU2YTQyOWRjYSJ9.DLPK3rTofvSS50pmlBm1xtDnThUuBLtBMqm7o9YjBoI"
JWT_SECRET="kdp12032003"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1